name: munchspace
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.3.1
  dtd: ^4.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_lints: ^6.0.0
  flutter_riverpod: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.2.2
  geolocator: ^10.1.0
  google_fonts: ^6.3.2
  google_maps_flutter: ^2.14.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconly: ^1.0.1
  intl: ^0.19.0
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  pinput: ^5.0.2
  riverpod: ^2.4.0
  stack_trace: ^1.12.1
  top_snackbar_flutter: ^3.3.0
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.6

  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/orders/
    - assets/svg/
    - assets/svg/home/
    - assets/svg/nav_bar/
    - assets/svg/address/
    - assets/svg/notification/
    - assets/svg/orders/
    - assets/svg/profile/
    - .env
