name: munchspace
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.2.2
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconly: ^1.0.1
  intl: ^0.19.0
  pinput: ^5.0.2
  riverpod: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.6

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/
    - assets/svg/
    - assets/svg/home/
    - assets/svg/nav_bar/
